feat: split install and run into two different steps
This allows the path to be properly updated when installing on a minimal
system

From the generated installer by cargo-dist
```
add_install_dir_to_ci_path() {
    # Attempt to do CI-specific rituals to get the install-dir on PATH faster
    local _install_dir="$1"

    # If GITHUB_PATH is present, then write install_dir to the file it refs.
    # After each GitHub Action, the contents will be added to PATH.
    # So if you put a curl | sh for this script in its own "run" step,
    # the next step will have this dir on PATH.
    #
    # Note that GITHUB_PATH will not resolve any variables, so we in fact
    # want to write install_dir and not install_dir_expr
    if [ -n "${GITHUB_PATH:-}" ]; then
        ensure echo "$_install_dir" >> "$GITHUB_PATH"
    fi
}
```

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -143,26 +143,13 @@ runs:
           const version = process.env.RUNNER_VERSION
           core.setOutput('hash', hashes[version] || '')
 
-    - shell: bash
-      env:
-        GH_MATRIX: "${{ toJson(matrix) }}"
-        GH_STRATEGY: "${{ toJson(strategy) }}"
-        # This is needed to properly handle quotes and multiline commands in the 'run' input properly, rather than doing `RUN_INPUT_RUN=${{ inputs.run }}` in the script
-        CODSPEED_INPUT_RUN: ${{ inputs.run }}
+    - name: Install CodSpeed runner
+      shell: bash
       run: |
-        # Validate required inputs
-        # (custom message for smoother v4 migration)
-        if [ -z "${{ inputs.mode }}" ]; then
-          echo "::error title=Missing required input 'mode'::The 'mode' input is required as of CodSpeed Action v4. Please explicitly set 'mode' to 'simulation' or 'walltime'. Before, this variable was automatically set to instrumentation on every runner except for CodSpeed macro runners where it was set to walltime by default. See https://codspeed.io/docs/instruments for details."
-          exit 1
-        fi
-
-        # Configure and run codspeed-runner
         RUNNER_VERSION="${{ steps.versions.outputs.runner-version }}"
         VERSION_TYPE="${{ steps.versions.outputs.version-type }}"
 
-        # Install the runner
-        SKIP_HASH_CHECK_WARNING_WARNING="${{ inputs.skip-hash-check-warning }}"
+        SKIP_HASH_CHECK_WARNING="${{ inputs.skip-hash-check-warning }}"
 
         if [ "$VERSION_TYPE" = "latest" ]; then
           if [ "$SKIP_HASH_CHECK_WARNING" != "true" ]; then
@@ -214,6 +201,21 @@ runs:
           echo "Installer hash verified for version $RUNNER_VERSION"
 
           bash "$INSTALLER_TMP" --quiet
+        fi
+
+    - name: Run the benchmarks
+      shell: bash
+      env:
+        GH_MATRIX: "${{ toJson(matrix) }}"
+        GH_STRATEGY: "${{ toJson(strategy) }}"
+        # This is needed to properly handle quotes and multiline commands in the 'run' input properly, rather than doing `RUN_INPUT_RUN=${{ inputs.run }}` in the script
+        CODSPEED_INPUT_RUN: ${{ inputs.run }}
+      run: |
+        # Validate required inputs
+        # (custom message for smoother v4 migration)
+        if [ -z "${{ inputs.mode }}" ]; then
+          echo "::error title=Missing required input 'mode'::The 'mode' input is required as of CodSpeed Action v4. Please explicitly set 'mode' to 'simulation' or 'walltime'. Before, this variable was automatically set to instrumentation on every runner except for CodSpeed macro runners where it was set to walltime by default. See https://codspeed.io/docs/instruments for details."
+          exit 1
         fi
 
         # Build the runner arguments array
