feat: integrate the native runner with a composite action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,15 +12,51 @@ inputs:
   run:
     description: "The command to run the benchmarks"
     required: true
+
   working-directory:
     description: |
       The directory where the `run` command will be executed.
       Warning: if you use defaults.working-directory, you must still set this parameter.
     required: false
-  upload_url:
+  upload-url:
     description: "The upload endpoint (for on-premise deployments)"
-    default: "https://api.codspeed.io/upload"
+    required: false
+
+  runner-version:
+    description: "The version of the runner to use"
+    default: "2.0.0"
     required: true
+
 runs:
-  using: "node16"
-  main: "dist/index.js"
+  using: "composite"
+  steps:
+    # Build the args string
+    - id: args
+      shell: bash
+      run: |
+        args=""
+        if [ -n "${{ inputs.token }}" ]; then
+          args="$args --token ${{ inputs.token }}"
+        fi
+        if [ -n "${{ inputs.working-directory }}" ]; then
+          args="$args --working-directory=${{ inputs.working-directory }}"
+        fi
+        if [ -n "${{ inputs.upload-url }}" ]; then
+          args="$args --upload-url=${{ inputs.upload-url }}"
+        fi
+        echo "args=$args" >> $GITHUB_OUTPUT
+
+    # Install the CodSpeedHQ/runner
+    - shell: bash
+      run: |
+        head_status=$(curl -I -fsSL -w "%{http_code}" -o /dev/null https://github.com/CodSpeedHQ/runner/releases/download/v${{ inputs.runner-version }}/codspeed-runner-installer.sh)
+        if [ "$head_status" -eq 404 ]; then
+          echo "Error: Version ${{ inputs.runner-version }} is not available in https://github.com/CodSpeedHQ/runner/releases, please a correct version."
+          exit 1
+        else
+          curl -fsSL https://github.com/CodSpeedHQ/runner/releases/download/v${{ inputs.runner-version }}/codspeed-runner-installer.sh | bash
+        fi
+
+    # Run the benchmarks
+    - shell: bash
+      run: codspeed-runner ${{ steps.args.outputs.args }} -- '${{ inputs.run }}'
